### ISSUE TITLE
Secure Sign-On Functionality

### ISSUE THREAD

**Issue by jamesgrady** [pHRma-Capstone/pHRma#5]
Need to simulate security on the frontend

Roles
- employee
- supervisor

**Comment by naroop** [comment]
waiting for backend to get set up so that we can add in real authentication

**Comment by naroop** [comment]
https://github.com/pHRma-Capstone/pHRma/assets/76455626/1dc3793b-db8f-4b34-91fc-2551ec46f85f

**Comment by naroop** [comment]
https://github.com/pHRma-Capstone/pHRma/assets/76455626/8c9a90db-4534-4527-9558-6dbab01de46f
